# --- 1. Dependencias (Cache) ---
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install --force


FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
RUN npm prune --production --force

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

USER node

EXPOSE 3000

CMD ["node", "dist/index.js"]